// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgH7CUZJwLs7sD5g68YBfFvbkpqp2LIFs',
    appId: '1:827510167007:web:bf9f754fadc201842f206a',
    messagingSenderId: '827510167007',
    projectId: 'snscanner-e22af',
    authDomain: 'snscanner-e22af.firebaseapp.com',
    storageBucket: 'snscanner-e22af.appspot.com',
    measurementId: 'G-DE3BVN2ZC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5gzIhtg6wIm3XL0976I-MxMzYZ5vvIs',
    appId: '1:827510167007:android:35f7bed78cb36fa22f206a',
    messagingSenderId: '827510167007',
    projectId: 'snscanner-e22af',
    storageBucket: 'snscanner-e22af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Ep2ve67aOldGmhHeR37h1Zz0U0nh7IM',
    appId: '1:827510167007:ios:1f4c060d7b85124d2f206a',
    messagingSenderId: '827510167007',
    projectId: 'snscanner-e22af',
    storageBucket: 'snscanner-e22af.appspot.com',
    iosBundleId: 'com.example.snscanner',
  );
}
